auto: true
markdown: rdiscount
pygments: true
exclude: ["README.md","nbproject"]

paginate: 10
paginate_path: page:num

website_url: http://a2lix.fr
website_title: A2LiX
website_author: David ALLIX
